## LANGUAGE
defaultContentLanguage: en
languageCode: en

## ADVANCED
build:
  writeStats: true
enableRobotsTXT: true
imaging:
  quality: 80
markup:
  tableOfContents:
    ordered: true
paginate: 18
removePathAccents: true
disableHugoGeneratorInject: true
