## LANGUAGE
defaultContentLanguage: fr
languageCode: fr

## ADVANCED
build:
  writeStats: true
enableRobotsTXT: true
imaging:
  quality: 80
markup:
  tableOfContents:
    ordered: true
paginate: 18
removePathAccents: true