_merge: deep
# offices: /cabinets/:slug/
# persons: /equipe/:slug/
# persons_offices: /equipe/cabinets/:slug/
# posts: /actualites/:year-:month-:day-:slug/
# authors: /actualites/authors/:slug/
# categories: /actualites/categories/:slug/
# tags: /actualites/tags/:slug/
# projects: /projets/:year-:slug/
# projects_types: /projets/types/:slug/
# projects_tags: /projets/tags/:slug/
# publications: /parutions/:slug/
# publications_concerned: /parutions/personnes-concernees/:slug/
